"""Descriptive registry for independent, close-confirmed stock research signals.

``active`` means the scanner has an evaluator, not a passed backtest or live
qualification. Catalog-only research is intentionally not evaluated as False.
This is an inventory of this repository and selected common rule families, not
an exhaustive list of internet strategies. Regime labels describe hypotheses;
they do not route orders or assert a validated advantage in that regime.

Keep this module free of prices, model loading, I/O and account state. A strategy
may match alongside any other strategy; exits, ranking, allocation and execution
are explicitly separate kinds. Historical performance never transfers merely
because a new adapter has a familiar name.
"""
from __future__ import annotations

from copy import deepcopy


VERSION = "scanner_catalog_v1_20261005"
_ENGINE = "skills/strategy_scanner/engine.py"
_FACTORY = "skills/strategy_factory/strategies.py"
_FINMIND_TECHNICAL = "https://finmind.github.io/tutor/TaiwanMarket/Technical/"
_VOLUME_PROFILE = "https://www.tradingview.com/support/solutions/43000502040-volume-profile-indicators-basic-concepts/"
_DONCHIAN = "https://www.tradingview.com/support/solutions/43000502253-donchian-channels-dc/"
_BOLLINGER = "https://www.bollingerbands.com/bollinger-band-rules"


def _item(identifier, name, family, kind, description, required_data, source_paths,
          *, active=False, regimes=(), variants=(), gaps=(), interfaces=(), urls=()):
    return {
        "id": identifier,
        "name": name,
        "family": family,
        "kind": kind,
        "status": "active" if active else "catalog_only",
        "description": description,
        "required_data": list(required_data),
        "preferred_regimes": list(regimes),
        "version": VERSION,
        "source_paths": list(source_paths),
        "source_urls": list(urls),
        "variants": list(variants),
        "data_gaps": list(gaps),
        "reusable_interfaces": list(interfaces),
        "live_qualified": False,
        "returns_inherited": False,
    }


CATALOG = (
    _item("original_breakout", "原封存價量突破", "price_breakout", "entry",
          "讀取完整原始候選帳本，重現其突破量增訊號；不以實際成交或持倉名額代替候選。",
          ("raw_ohlcv", "historical_eligibility", "complete_original_candidate_ledger"),
          (_ENGINE, "skills/stock_universe_2019.py", "docs/prereg_stock_universe_2019_20260929.md"),
          active=True, regimes=("trend_up",),
          gaps=("缺完整且來源綁定的候選帳本時為未知；不能用部分交易紀錄判定其他股票沒有訊號。",)),
    _item("original_red", "原突破＋紅 K", "price_breakout", "entry",
          "原封存候選且訊號日原始收盤嚴格高於開盤；同價 K 不算紅 K。",
          ("raw_ohlcv", "historical_eligibility", "complete_original_candidate_ledger"),
          (_ENGINE, "skills/candle_volume_rules.py", "docs/prereg_candle_volume_account_20261003.md"),
          active=True, regimes=("trend_up",), interfaces=("CandleVolumeSignals.red_entry",)),
    _item("poc_red_priority", "POC 優先＋紅 K（原研究語意）", "volume_profile", "ranking",
          "是否符合仍由原突破＋紅 K 決定；POC 上移只提供優先排序，POC 未知不冒充已上移。這不是 POC 硬門檻。",
          ("raw_ohlcv", "complete_original_candidate_ledger", "prior20_regular_session_ticks", "corporate_action_scale"),
          (_ENGINE, "skills/volume_profile_selection.py", "skills/poc_daily_opportunities.py", "docs/prereg_poc_daily_opportunities_20261004.md"),
          active=True, regimes=("trend_up",),
          gaps=("部分股票日期缺逐筆或來源品質確認；保留 POC 未知，與紅 K 候選狀態分開。",),
          interfaces=("AccountProfileData.__call__", "build_volume_profile"), urls=(_VOLUME_PROFILE,)),
    _item("poc_up_red", "POC 上移＋紅 K（獨立硬篩研究版）", "volume_profile", "entry",
          "原突破＋紅 K 且前 20 個交易日後半段 POC 高於前半段 POC；不含訊號日，未知 POC 不通過也不填成 false。",
          ("raw_ohlcv", "complete_original_candidate_ledger", "prior20_regular_session_ticks", "corporate_action_scale"),
          (_ENGINE, "skills/volume_profile.py", "skills/volume_profile_data.py", "docs/prereg_volume_profile_20261003.md"),
          active=True, regimes=("trend_up",),
          gaps=("需 20 日同口徑逐筆與可比價格尺度；未覆蓋的紅 K 候選為未知。此硬篩版不繼承原 POC 優先帳戶績效。",),
          interfaces=("build_volume_profile", "AccountProfileData.__call__"), urls=(_VOLUME_PROFILE, _FINMIND_TECHNICAL)),
    _item("momentum", "中期動能", "momentum", "entry",
          "126 至 21 日前的價格動能為正、收盤高於 MA120、20 日平均估計成交值至少 5,000 萬；每日顯示條件，原研究為月頻配置。",
          ("adjusted_close", "raw_close_times_volume", "market_calendar", "historical_eligibility"),
          (_ENGINE, "skills/rule_research.py", "docs/prereg_rules_20260909.md"),
          active=True, regimes=("trend_up",), interfaces=("scores_for",)),
    _item("risk_momentum", "波動調整動能", "momentum", "ranking",
          "中期動能條件成立且 126 日波動有效；分數為動能除以年化波動。它是動能名單內的另一種排序，不保證較低回撤。",
          ("adjusted_close", "raw_close_times_volume", "market_calendar", "historical_eligibility"),
          (_ENGINE, "skills/rule_research.py", "docs/prereg_rules_20260909.md"),
          active=True, regimes=("trend_up",), interfaces=("scores_for",)),
    _item("near_high", "接近一年新高", "momentum", "entry",
          "收盤在 252 日最高收盤的 95% 以上、MA60 高於 MA120、63 日漲幅為正，並符合 5,000 萬估計成交值門檻。",
          ("adjusted_close", "raw_close_times_volume", "market_calendar", "historical_eligibility"),
          (_ENGINE, "skills/rule_research.py", "docs/prereg_rules_20260909.md"),
          active=True, regimes=("trend_up",), interfaces=("scores_for",)),
    _item("contraction_breakout", "收斂後帶量突破", "price_breakout", "entry",
          "前 10 日高低區間不超過再前 10 日的 75%，收盤突破不含今日的 20 日高點，量至少為此前 20 日均量 1.5 倍；估計成交值門檻 5,000 萬。",
          ("raw_ohlcv", "adjusted_close", "raw_close_times_volume", "market_calendar"),
          (_ENGINE, "skills/technical_signals.py", "docs/prereg_technical_20260910.md"),
          active=True, regimes=("trend_up", "range"), interfaces=("TechnicalSignals.technical_context",)),
    _item("donchian20", "20 日價格通道突破", "price_breakout", "entry",
          "今日收盤嚴格突破此前 20 個交易日最高價；不把今日高價放入門檻，估計成交值 20 日均值至少 5,000 萬。",
          ("raw_ohlcv", "adjusted_close", "raw_close_times_volume", "market_calendar"),
          (_ENGINE,), active=True, regimes=("trend_up", "range"), urls=(_DONCHIAN,)),
    _item("donchian55", "55 日價格通道突破", "price_breakout", "entry",
          "今日收盤嚴格突破此前 55 個交易日最高價；搭配 5,000 萬估計成交值門檻。這是通道條件，並非整套海龜交易系統。",
          ("raw_ohlcv", "adjusted_close", "raw_close_times_volume", "market_calendar"),
          (_ENGINE,), active=True, regimes=("trend_up", "range"), urls=(_DONCHIAN,)),
    _item("bollinger_reclaim", "跌出布林下軌後收回", "mean_reversion", "entry",
          "昨收低於當時布林下軌，今日紅 K 且收回當日下軌內；20 日均線、兩倍母體標準差，估計成交值門檻 5,000 萬。這是新適配研究條件。",
          ("raw_ohlcv", "adjusted_close", "raw_close_times_volume", "market_calendar"),
          (_ENGINE,), active=True, regimes=("range",), urls=(_BOLLINGER,)),
    _item("ma_pullback", "上升趨勢回測均線", "pullback", "entry",
          "今日及昨日 MA20 均高於 MA60；今日低價觸及 MA20 的 1.01 倍以下，最後紅 K 收在 MA20 上；估計成交值門檻 5,000 萬。",
          ("raw_ohlcv", "adjusted_close", "raw_close_times_volume", "market_calendar"),
          (_ENGINE,), active=True, regimes=("trend_up",)),

    # Existing research entries. These are not yet adapters in the daily scanner.
    _item("first_volume_bar", "盤整後第一根帶量紅 K", "early_launch", "entry",
          "前 20 日收盤區間不超過 15%，今日量至少此前均量兩倍、漲至少 2%、紅 K 且收於高位 35%；前 10 日未有相同脈衝，事件冷卻 21 日。",
          ("raw_ohlcv", "adjusted_close", "historical_eligibility", "market_calendar"),
          ("skills/first_bar.py", "docs/prereg_first_bar_20260927.md"),
          regimes=("range", "trend_up"), variants=("first", "wait_for_breakout", "with_chips"),
          gaps=("需把既有事件研究轉成全市場逐日三態適配器；既有母體使用現有公司快照，並非完整歷史名冊。",),
          interfaces=("first_bar.features", "first_bar.episodes", "first_bar.wait_for_breakout")),
    _item("first_bar_confirmation", "第一根後守穩或回測", "early_launch", "entry",
          "沿用第一根事件，比較立即、三日守住且縮量、五日內回測後收回；相對強度由弱轉強可另加。確認完成前不能產生買訊。",
          ("first_volume_bar_events", "raw_ohlcv", "adjusted_close", "benchmark_prices", "market_calendar"),
          ("skills/early_strength.py", "docs/prereg_early_strength_20260927.md"),
          regimes=("trend_up",), variants=("all_first", "all_confirm3", "all_retest5", "turn_first", "turn_confirm3", "turn_retest5"),
          gaps=("新掃描尚未接入逐日事件狀態；尚未滿確認窗口為未知或等待，不可回填到第一根當天。",),
          interfaces=("early_strength.event_features", "early_strength.decisions")),
    _item("early_rotation", "資金轉熱與早期相對強勢", "early_launch", "entry",
          "比較相對 0050 強勢、60 日突破、近 5 日估計成交值升溫，以及靠近高點但尚未大漲的交集；不使用事後急漲標籤作進場。",
          ("adjusted_close", "raw_close_times_volume", "benchmark_prices", "historical_eligibility"),
          ("skills/stock_launch.py", "docs/prereg_stock_launch_20260927.md"),
          regimes=("range", "trend_up"), variants=("relative_strength", "breakout60", "turnover_heat", "breakout_strength", "money_strength", "early_rotation"),
          gaps=("舊研究有指定案例與固定觀察日；尚未接全股逐日掃描。未來 20／60 日急漲只能當結果標籤。",),
          interfaces=("stock_launch.features",)),
    _item("revenue_growth", "營收成長與加速", "fundamental", "entry",
          "三個月合計營收年增至少 20%，且年增率較三個月前加速；可再與價格趨勢、法人買超交叉。",
          ("monthly_revenue", "original_publication_versions", "available_at", "adjusted_close", "raw_close_times_volume"),
          ("skills/revenue_research.py", "docs/prereg_revenue_20260909.md"),
          regimes=("trend_up",), variants=("revenue", "revenue_price", "revenue_price_trust"),
          gaps=("歷史原始公告時刻及修訂版本未完整；原 45／60 日延遲是假設，不是已驗證 PIT。",),
          interfaces=("revenue_features", "revenue_scores")),
    _item("revenue_surprise", "營收超過季節性預期", "fundamental", "filter",
          "以前三個月和去年同期推估本月營收，實際值高於模型預期至少 10%；它是營收預測誤差，不是分析師共識。",
          ("monthly_revenue", "original_publication_versions", "available_at"),
          ("skills/earnings_expectations.py", "docs/prereg_priority_20260924.md"),
          regimes=("trend_up", "range"), variants=("revenue_covered", "surprise", "surprise_quality"),
          gaps=("歷史首刊／更正版本與實際可得時點不足，15／30 日延遲僅研究假設；尚未每日掃描。",),
          interfaces=("expected_revenue", "revenue_daily", "earnings_expectations.filter_entries")),
    _item("financial_quality", "獲利轉折與財務品質", "fundamental", "filter",
          "既有品質規則要求毛利率優於去年同季且稅後淨利為正；營業現金流與更完整體質檢查須另定規格，不能宣稱目前已具備。",
          ("quarterly_revenue", "quarterly_gross_profit", "quarterly_net_income", "original_publication_versions", "available_at"),
          ("skills/earnings_expectations.py", "skills/ingest_quarterly_fundamental.py", "skills/quarterly_validation.py"),
          variants=("quality_covered", "surprise_quality"),
          gaps=("季末不是公告日；原 120／150 日延遲為假設。需要完整首刊財報、修訂時點與科目口徑。",),
          interfaces=("quality_daily",)),
    _item("guidance_surprise", "財測超預期與上修", "fundamental", "entry",
          "當期實際營收超過先前已公布的財測上緣，另比價格確認及同年度財測上修；對照的是事前財測版本。",
          ("historical_guidance_documents", "actual_operating_results", "original_publication_versions", "available_at", "raw_ohlcv"),
          ("skills/guidance_signals.py", "docs/prereg_guidance_20260910.md"),
          variants=("beat", "beat_confirm", "guidance_up", "combined"),
          gaps=("現有正式比較主要為 2330 個案；缺全市場結構化財測與逐版發布時點，不能當成全股掃描。",),
          interfaces=("quarterly_comparison", "version_signal_index", "guidance_signals.build_signals")),
    _item("revenue_pead", "月營收公告後漂移", "fundamental", "entry",
          "依營收年增或加速做截面排序，研究公告後的報酬漂移；既有按申報截止日代理的回测不能直接視為真實公告事件。",
          ("monthly_revenue", "original_publication_versions", "available_at", "historical_eligibility"),
          ("scripts/backtest_pead.py", "docs/prereg_pead_arm_20260711.md", "docs/prereg_pead_rank_arm_20260711.md"),
          variants=("revenue_yoy", "revenue_yoy_accel", "cross_sectional_rank"),
          gaps=("缺逐股首刊與修訂歷史；必須重核營收月份標籤和公告時序。不能把延遲進場的結果保證為效果下界。",)),
    _item("theme_catalyst", "可核實催化事件＋價量", "theme", "entry",
          "以公告中的訂單、認證、量產、出貨或已實現題材營收確認催化，再要求價格突破與相對強勢；意向或傳聞不等同營運證據。",
          ("dated_theme_membership", "company_announcements", "original_publication_versions", "available_at", "adjusted_close", "raw_ohlcv"),
          ("skills/theme_catalyst.py", "docs/prereg_theme_catalyst_20260927.md"),
          regimes=("trend_up",), variants=("watchlist_breakout", "confirmed_catalyst"),
          gaps=("既有官方事件簿只涵蓋有限低軌衛星個案；歷史假設模式與實際觀測模式須分開，尚非全市場事件抽取。",),
          interfaces=("validate_ledger", "evidence_state", "theme_catalyst.build_signals")),
    _item("news_event_group", "新聞事件與同群確認", "theme", "entry",
          "將漲價、訂單、量產等新聞分類，與當時同行股的價格及量能反應交叉；事件、群組、交集分開研究。",
          ("news_first_publication", "news_revision_history", "dated_theme_membership", "raw_ohlcv"),
          ("skills/event_group_research.py", "skills/news_radar.py", "docs/prereg_event_groups_20260909.md"),
          variants=("event", "group", "combined"),
          gaps=("部分新聞供應商日期不等於首刊日期；缺完整歷史文本／公司受益證據，不能用今日題材標籤回推。",),
          interfaces=("classify_event", "extract_news", "peer_confirmation", "event_group_research.build_signals")),
    _item("group_diffusion", "龍頭啟動與族群接力", "sector_rotation", "entry",
          "用過去 126 日價格殘差形成當月固定群組；領先股突破後，觀察其他成員廣度及成交占比是否依序擴散。",
          ("adjusted_close", "raw_close_times_volume", "benchmark_prices", "historical_eligibility", "market_calendar"),
          ("skills/diffusion_signals.py", "skills/historical_diffusion_signals.py", "docs/prereg_diffusion_20260910.md"),
          regimes=("trend_up",), variants=("leader_now", "leader_after", "follower_after", "basket_after"),
          gaps=("價格同行群不是已核實產業链；需完整歷史母體、每月凍結分群和每日事件狀態適配。",),
          interfaces=("diffusion_signals.build_diffusion", "historical_diffusion_signals.build_diffusion")),
    _item("holder_strength", "持股集中＋相對強勢", "chip", "entry",
          "比較大戶持股比例與實際股數增加、小戶比例下降，以及相對 0050 強勢；集保級距不能識別同一實益持有人。",
          ("weekly_holder_distribution", "holder_publication_history", "issued_shares", "adjusted_close", "benchmark_prices"),
          ("skills/theme_chips.py", "skills/holder_flow.py", "docs/prereg_theme_chips_20260927.md", "docs/prereg_holder_flow_20260927.md"),
          variants=("concentration", "relative_strength", "both", "foreign_trust_combinations"),
          gaps=("週資料觀測日不等於公告時刻；原加 8／15 日為假設，需首刊歷史與總股數一致性。",),
          interfaces=("theme_chips.conditions", "holder_flow.combine")),
    _item("institutional_absorption", "法人賣壓下價格抗跌", "chip", "entry",
          "法人五日賣壓達門檻，價格仍守住並未弱於 0050，作為承接假說；不能据此證明是大戶接貨或散戶踩踏。",
          ("daily_institutional_flow", "institutional_available_at", "adjusted_close", "raw_volume", "benchmark_prices"),
          ("skills/absorption.py", "docs/prereg_absorption_20260927.md"),
          variants=("buy_pressure", "sell_pressure", "resilient", "absorption", "sell_weak"),
          gaps=("原研究採固定觀察日，法人資料延遲 1／3 日是假設；需要完整每日覆蓋與首次可得時點。",),
          interfaces=("absorption.candidates",)),
    _item("ml_ranker", "既有 ML 排序研究", "machine_learning", "ranking",
          "以當時可用特徵與訓練截止版本產生股票分數；模型分數與其他策略原始分數不可直接比較。",
          ("point_in_time_features", "training_cutoff", "frozen_model", "feature_schema", "historical_eligibility"),
          ("skills/train_ranker.py", "skills/build_features.py", "skills/training_cache.py", "docs/prereg_d_revalidation_20260710.md"),
          variants=("ranker", "multi_horizon", "stacking", "meta_label"),
          gaps=("需鎖定模型／特徵版本、訓練截止與資料可得性；舊研究報酬不轉移到本日掃描器，尚未接入。",)),

    # Six legacy factory configurations are separate from the newer adapters.
    _item("legacy_momentum_trend", "舊工廠：MomentumTrend", "legacy_factory", "entry",
          "收盤高於 MA60、20 日漲幅超過 10%、20 日均量高於 60 日均量，估計成交值至少 0.5 億。",
          ("adjusted_close", "raw_volume", "raw_close_times_volume"), (_FACTORY, "skills/strategy_factory/data.py"),
          regimes=("trend_up",), gaps=("舊工廠未接新三態掃描器；不可連同其持倉／成交引擎直接搬入。",),
          interfaces=("MomentumTrend.entry_rules",)),
    _item("legacy_mean_reversion", "舊工廠：MeanReversion", "legacy_factory", "entry",
          "RSI14 低於 30 且收盤低於布林下軌、估計成交值至少 0.5 億；與等待收回下軌的新策略不同。",
          ("adjusted_close", "raw_close_times_volume"), (_FACTORY, "skills/strategy_factory/data.py"),
          regimes=("range",), gaps=("舊 RSI／布林公式和缺值語意需版本鎖定；尚未接新掃描。",),
          interfaces=("MeanReversion.entry_rules",)),
    _item("legacy_defensive_low_vol", "舊工廠：DefensiveLowVol", "legacy_factory", "entry",
          "60 日波動在當日股票截面最低 30%，且收盤高於 MA20、估計成交值至少 0.5 億。",
          ("adjusted_close", "complete_cross_section", "raw_close_times_volume"), (_FACTORY, "skills/strategy_factory/data.py"),
          gaps=("缺截面不能補中位排名；歷史完整母體與三態排名適配尚未完成。",),
          interfaces=("DefensiveLowVol.entry_rules",)),
    _item("legacy_course_volume", "舊工廠：CourseVolumeMomentum", "legacy_factory", "entry",
          "收盤高於 MA20、20 日漲幅超過 10%、均量增及外資三日淨買超至少 1000 個來源單位，估計成交值至少 5 億。",
          ("adjusted_close", "raw_volume", "raw_close_times_volume", "daily_institutional_flow", "institutional_available_at"),
          (_FACTORY, "skills/strategy_factory/data.py"), regimes=("trend_up",),
          gaps=("須確認法人欄位單位／公告時點，舊載入會把缺法人值補零；不能沿用此缺值處理。",),
          interfaces=("CourseVolumeMomentum.entry_rules",)),
    _item("legacy_course_breakout", "舊工廠：CourseBreakout", "legacy_factory", "entry",
          "收盤達 400 日最高收盤的 99.8%，且當日量達 10 日最大量、估計成交值至少 5 億。舊窗口含當日，非新通道定義。",
          ("adjusted_close", "raw_volume", "raw_close_times_volume"), (_FACTORY, "skills/strategy_factory/data.py"),
          regimes=("trend_up",), gaps=("需足夠 400 日暖機並鎖定含當日窗口；尚未接新掃描。",),
          interfaces=("CourseBreakout.entry_rules",)),
    _item("legacy_course_pullback", "舊工廠：CoursePullback", "legacy_factory", "entry",
          "收盤高於 MA60、距 MA10 不超過 3%、RSI14 低於 45、法人同向，估計成交值至少 0.8 億；舊同向公式也包含外資投信同賣。",
          ("adjusted_close", "daily_institutional_flow", "institutional_available_at", "raw_close_times_volume"),
          (_FACTORY, "skills/strategy_factory/data.py"), regimes=("trend_up",),
          gaps=("法人同向不等於同買；缺值补零及時點需重新適配，不能以名稱推論規則。",),
          interfaces=("CoursePullback.entry_rules",)),

    # Entry overlays and context do not become independent purchase instructions.
    _item("institutional_flow", "法人連買與價量交叉", "chip", "filter",
          "比較外資／投信多日淨買超占成交量、連買天數、增量及均線；另有 20 日投信買超和量能轉強組。",
          ("daily_institutional_flow", "institutional_available_at", "raw_volume", "adjusted_close"),
          ("skills/flow_research.py", "skills/launch_flows.py", "skills/chip_research.py", "docs/prereg_flow_20260909.md", "docs/prereg_launch_flows_20260927.md"),
          variants=("trust", "volume", "trust_volume", "foreign_streak3", "trust_streak3", "both_positive5", "streak_and_trend"),
          gaps=("完整發布時點與修訂歷史未認證；不能把查無資料當淨買超零，尚未接每日適配。",),
          interfaces=("flow_scores", "launch_flows.flow_features", "launch_flows.attach_rules", "ChipSignals")),
    _item("margin_lending_repair", "融資／借券修復", "chip", "filter",
          "觀察融資餘額或借券賣出餘額下降，同時股價守穩、法人參與；餘額與借券成交量必須分開。",
          ("margin_balance", "borrowed_short_balance", "corporate_action_scale", "daily_institutional_flow", "available_at"),
          ("skills/chip_research.py", "docs/prereg_chip_20260911.md"),
          variants=("margin_repair", "lending_repair", "institutional_price_combination"),
          gaps=("需完整連續餘額、股本調整與發布時點；現有候選覆蓋不等於全股逐日完整。",),
          interfaces=("ChipSignals",)),
    _item("broker_concentration", "券商分點集中與指定分點", "broker", "filter",
          "依分點合計淨買超、前五名占比與方向性篩選既有候選；指定分點必須能唯一對應代碼。不能從分點推論真實持有人。",
          ("broker_branch_transactions", "broker_identity_history", "broker_available_at", "buy_sell_reconciliation"),
          ("skills/broker_branch_diagnostics.py", "skills/chip_research.py", "docs/prereg_broker_branch_20261004.md"),
          variants=("named_positive", "concentration", "directional_ratio", "combined"),
          gaps=("原母體只有部分候選；需要全股日覆蓋及來源買賣平衡核對。模糊地名不猜分點。",),
          interfaces=("branch_snapshot", "broker_concentration")),
    _item("broker_persistence", "券商分點連續承接", "broker", "filter",
          "固定窗口內追蹤同一分點是否連續淨買超，再与原訊號交叉；與單日爆買分開。",
          ("broker_branch_transactions", "broker_identity_history", "broker_available_at", "market_calendar"),
          ("skills/broker_persistence.py", "docs/prereg_broker_persistence_20260924.md", "docs/prereg_poc_broker_account_20261004.md"),
          variants=("persistence", "poc_plus_persistence"),
          gaps=("缺日不能當未買；新掃描尚無完整連續分點適配，分點交易也不等於持有庫存。",),
          interfaces=("select_branches", "validate_interval", "persistence")),
    _item("sector_breadth_flow", "族群廣度與成交占比", "sector_rotation", "context",
          "排除目標股票後，檢查同行股相對強弱廣度與成交占比是否增加；成交值活躍度不是資金淨流入。",
          ("point_in_time_sector_membership", "whole_market_prices", "whole_market_turnover", "benchmark_prices"),
          ("skills/surge_sector.py", "docs/prereg_surge_sector_20260925.md"),
          variants=("sector_breadth", "sector_relative_strength", "sector_turnover_share", "combined"),
          gaps=("既有產業名單 membership_point_in_time=false；歷史掃描不能直接用今日分類回填，分母覆蓋不足也應未知。",),
          interfaces=("sector_features",)),
    _item("chain_flow_context", "供應鏈法人與市場背景", "sector_rotation", "context",
          "比較同鏈公司法人買賣與價格表現，作候選的背景證據；需有當時已知的公司關聯而非事後赢家名單。",
          ("point_in_time_supply_chain", "daily_institutional_flow", "available_at", "raw_ohlcv"),
          ("skills/chain_flow.py", "docs/prereg_chain_flow_20260909.md"),
          gaps=("產業鏈歷史成員與法人首刊時點不足；仍為有限名單背景診斷，非每日獨立買訊。",),
          interfaces=("institutional_net",)),
    _item("entry_quality", "乖離、強勢收盤與市場廣度", "entry_quality", "filter",
          "獨立比較不過度乖離、紅 K 收在全日高位 30%、合資格股站上 MA20 廣度至少一半且未轉差；不任意把各組全部疊加。",
          ("raw_ohlcv", "adjusted_close", "whole_market_prices", "historical_eligibility"),
          ("skills/entry_filters.py", "skills/candidate_quality.py", "docs/prereg_entry_filters_20260930.md", "docs/prereg_candidate_quality_20260929.md"),
          variants=("not_extended", "strong_close", "breadth", "contraction"),
          gaps=("尚未接新日掃描；全日同價、缺廣度分母不得補成通過。",),
          interfaces=("filter_features", "apply_filters", "candidate_features")),
    _item("liquidity_filter", "持續流動性", "liquidity", "filter",
          "在原候選上比較成交值中位數、排除訊號日的前 20 日均值，以及兩者同時至少 5,000 萬；估計成交值使用收盤乘股數。",
          ("raw_close", "raw_volume", "market_calendar"),
          ("skills/liquidity_candidates.py", "docs/prereg_liquidity_screen_20261001.md", "docs/prereg_liquidity_universe_20261001.md"),
          variants=("median50m", "prior50m", "persistent50m"),
          gaps=("成交值門檻不是防操縱保證，亦不證明指定價位能成交；新掃描尚未輸出這三個獨立 overlay。",),
          interfaces=("filter_candidates",)),
    _item("first_signal_episode", "連續合格訊號只取第一天", "entry_quality", "filter",
          "完整市場日曆上連續紅 K 合格原候選只保留第一天；名額滿或買不到不重設，與『第一根爆量』是不同定義。",
          ("complete_original_candidate_ledger", "raw_ohlcv", "complete_market_calendar", "pre_start_history"),
          ("skills/poc_first_signal.py", "docs/prereg_poc_range_first_20261005.md"),
          gaps=("需要起始日前歷史才能判斷 episode；新掃描的 first_signal 欄僅描述首次符合，不自動啟用這個交易過濾。",),
          interfaces=("first_signal_entries", "audit_first_signal")),
    _item("leader_chip_rank", "龍頭與籌碼排序", "chip", "ranking",
          "用相對強弱及當時籌碼對既有候選排序，分別比較只排序、硬篩及資料覆蓋控制；不能以是否最後買入定義訊號。",
          ("complete_original_candidate_ledger", "daily_institutional_flow", "weekly_holder_distribution", "available_at"),
          ("skills/leader_chip_replay.py", "docs/prereg_leader_chip_20260928.md"),
          variants=("baseline", "rank", "filter", "coverage"),
          gaps=("歷史資料時點仍需認證；舊 Replay 與名額相連，應只重用特徵／排序純函式。",),
          interfaces=("leader_chip_replay.features", "leader_chip_replay.choose")),
    _item("market_regime", "市場情境與系統性風險", "market_context", "context",
          "利用當時市場趨勢、廣度與已觀測風險，描述偏多、偏弱或盤整；戰爭、升息消息須另有可得時點，不事後貼標。",
          ("benchmark_prices", "whole_market_prices", "risk_publication_history", "available_at"),
          ("skills/regime_state.py", "skills/market_context.py", "skills/observed_risk.py", "docs/prereg_regime_switch_20260910.md", "docs/prereg_observed_risk_20260913.md"),
          variants=("trend", "breadth", "observed_risk"),
          gaps=("尚無已驗證的情境→策略獲利映射；事件機率與新聞時序資料不足，不能把描述標籤當自動擇時證據。",),
          interfaces=("build_trend", "execution_controls", "gate_events")),
    _item("chart_patterns", "W 底、頭肩底與其他型態", "chart_pattern", "entry",
          "可建立機械式轉折點及確認線規則；目前收斂突破已有明確公式，不能因此宣稱 W 底、頭肩底等型態都已实现。",
          ("adjusted_ohlc", "market_calendar", "causal_pivot_confirmation"),
          ("skills/technical_signals.py", "skills/pattern_cash_replay.py", "docs/prereg_technical_20260910.md", "docs/prereg_pattern_cash_20260927.md"),
          variants=("w_bottom_proposal", "inverse_head_shoulders_proposal", "triangle_proposal"),
          gaps=("缺事前固定的可運行型態定義及因果轉折確認；不可使用需要右側未來 K 棒的未確認 pivot。",)),

    # A scanner cannot decide these without a position or a separate virtual path.
    _item("scenario_exit", "固定停損、期限與轉弱出場", "exit", "exit",
          "比較 63 日期限、入場基準跌 12%、趨勢／大盤轉弱、強勢延長至 126 日等。出場訊號不等於成交。",
          ("position_entry_state", "adjusted_close", "benchmark_prices", "market_calendar"),
          ("skills/exit_policy.py", "skills/scenario_exit_replay.py", "docs/prereg_exit_scenarios_20260910.md"),
          variants=("fixed63", "loss12", "trail20_12", "weak20", "market_weak", "trend126", "adaptive"),
          gaps=("需要獨立持倉或每個訊號的虛擬路徑；未成交出場需保持鎖定及重試，不是全股無狀態進場策略。",),
          interfaces=("decide_exit",)),
    _item("three_black_exit", "進場後連續三根黑 K", "exit", "exit",
          "僅從進場後有效 K 棒起算，連續三根黑 K 且收盤逐日降低才出場；不把進場前的黑 K 算入。",
          ("position_entry_state", "raw_ohlcv", "corporate_action_scale", "market_calendar"),
          ("skills/three_black_exit.py", "skills/independent_three_black.py", "docs/prereg_three_black_exit_20261001.md"),
          gaps=("需要入場日及連續完整行情；新無持倉掃描只列出規則，不產生帳戶賣單。",)),
    _item("peak_drawdown_exit", "持有高點回落與收盤確認", "exit", "exit",
          "由持有期間高點計算回落門檻，比較收盤觸發次日賣、盘中跌破、收盤確認等；不可混用高點定義與成交時序。",
          ("position_entry_state", "adjusted_ohlc", "corporate_action_scale", "intraday_execution_evidence"),
          ("skills/peak_stop_research.py", "skills/intraday_peak_exit.py", "skills/close_confirmed_exit.py", "docs/prereg_peak_stop15_20260929.md", "docs/prereg_close_confirmed_20260929.md"),
          variants=("peak15_close", "intraday_peak", "close_confirmed"),
          gaps=("盤中觸發要有事件先後及成交證據；日高低代理不能證明已在停損價成交。",)),
    _item("support_value_exit", "支撐或價值區失守", "exit", "exit",
          "以入場前可知支撐或固定 VAH 觀察收盤失守，次日提出出場；不得以未來重新畫出的支撐回頭修改。",
          ("position_entry_state", "adjusted_ohlc", "entry_frozen_profile", "prior20_regular_session_ticks"),
          ("skills/support_risk_replay.py", "skills/volume_profile_account_adapter.py", "docs/prereg_support_risk_current_20260927.md", "docs/prereg_volume_profile_20261003.md"),
          variants=("support_failure", "fixed_vah_failure"),
          gaps=("需入場當時凍結支撐與有效 POC／VAH，不可用現今 profile 代替歷史基準。",)),
    _item("volume_stagnation_exit", "買後縮量、不漲與弱勢換股", "exit", "exit",
          "比較買後縮量、持有多日未有效上漲、弱於基準和跌破均線等失敗條件；等待天數與價格確認須用固定版本。",
          ("position_entry_state", "raw_volume", "adjusted_close", "benchmark_prices", "market_calendar"),
          ("skills/candle_volume_rules.py", "skills/waiting_exit.py", "skills/holding_release.py", "skills/rotation_2024.py", "docs/prereg_waiting_exit_20260930.md", "docs/prereg_holding_release_20260929.md"),
          variants=("volume_dryup", "waiting_exit", "failed_base", "stagnant"),
          gaps=("縮量本身不證明行情結束；需指定持倉起點、等待窗口及組合條件，未作無持倉買訊。",)),
    _item("reentry", "出場後轉強買回", "reentry", "entry",
          "先有虛擬或真實出場，之後收復指定價位或連續確認才重新進場；不會抹去此前已觸發的退出。",
          ("prior_exit_state", "adjusted_close", "market_calendar", "historical_eligibility"),
          ("skills/close_reentry.py", "docs/prereg_close_reentry_20260929.md"),
          variants=("reclaim", "confirm2"),
          gaps=("屬需路徑狀態的進場策略；須為每個獨立原始訊號建虛擬狀態，不能直接讀實際三檔持倉作全市場門檻。",),
          interfaces=("recovered", "CloseReentry")),

    _item("portfolio_slots", "持股名額、等權與產業分散", "allocation", "allocation",
          "比較三檔、五檔、單股上限和分散；只影響如何分配已產生的機會，不得讓未買候選從訊號日曆消失。",
          ("independent_signal_ledger", "account_cash", "positions", "corporate_entitlements"),
          ("skills/allocation_2019.py", "skills/conservative_diversification.py", "docs/prereg_stock_universe_five_20260929.md", "docs/prereg_cash_allocation_20260910.md"),
          variants=("max3", "max5", "equal_budget", "diversification"),
          gaps=("屬完整帳戶層，需重新演算現金／名額路徑；不能由独立訊號平均報酬推導帳戶報酬。",)),
    _item("risk_budget", "支撐風險與波動配置", "allocation", "allocation",
          "依支撐距離、波動和帳戶風險預算調整買入股數；有預算不等於停損必能成交。",
          ("account_nav", "positions", "support_distance", "historical_volatility", "execution_capacity"),
          ("skills/support_risk_replay.py", "skills/volatility_budget_replay.py", "skills/position_sizing.py", "docs/prereg_volatility_budget_20260927.md"),
          variants=("support_risk", "volatility_budget", "fixed_weight"),
          gaps=("需要帳戶狀態與可成交量，不能當獨立選股條件；最大虧損偏好不是可保證的實際回撤上限。",)),
    _item("pyramiding", "強勢股加碼", "allocation", "allocation",
          "符合續強或突破條件後對已有部位加碼，與首次選股訊號分開記錄；仍受現金、風險、容量和公司行動限制。",
          ("positions", "entry_cost_basis", "account_cash", "adjusted_ohlc", "execution_capacity"),
          ("skills/pyramid_cash_replay.py", "docs/prereg_pyramid_cash_20260927.md"),
          gaps=("需完整持倉及成本狀態；加碼不能被算成另一個全新獨立股票機會。",)),
    _item("rotation_queue", "候選排隊、換股與名額釋放", "allocation", "allocation",
          "當出現更強候選或原持股久未表現時，依凍結規則換股；排隊訊號的續存需逐日確認，不能未來挑贏家。",
          ("independent_signal_ledger", "positions", "account_cash", "adjusted_close", "market_calendar"),
          ("skills/candidate_queue_replay.py", "skills/holding_release.py", "skills/rotation_2024.py", "skills/slot_reuse_replay.py", "docs/prereg_rotation_2024_20260929.md"),
          variants=("candidate_queue", "stagnant", "stronger", "slot_reuse"),
          gaps=("屬投組路徑，不應在每日訊號偵測層刪除名額已滿的個股。",)),
    _item("account_drawdown_control", "帳戶降水位與冷卻", "allocation", "allocation",
          "帳戶回撤或市場轉弱時調整總曝險、分批退出與重新啟動；閒錢持現金和配置 0050 為不同資產配置。0050 不是避險保證。",
          ("account_nav", "account_high_watermark", "positions", "benchmark_prices", "market_context"),
          ("skills/drawdown_control.py", "skills/partial_risk.py", "skills/cash_risk_replay.py", "skills/index_exposure_replay.py", "docs/prereg_drawdown_control_20261001.md"),
          variants=("weak20", "half15", "cooldown", "partial_risk", "cash", "index_exposure"),
          gaps=("需獨立風控帳戶重播；不能聲稱訊號掃描已證明降水位後可避開全面下跌。",)),

    _item("price_execution_models", "開盤、日區間與逐筆成交", "execution", "execution",
          "T 收盤確認後最早下一交易日執行；比較開盤、各通路 HL2、買 70%／賣 30% 日區間代理及普通盤逐筆限制撮合，並非進場策略。",
          ("scheduled_orders", "channel_prices", "official_limit_band", "channel_volume", "execution_costs"),
          ("skills/opening_entry_replay.py", "skills/poc_range_execution.py", "skills/poc_executable_replay.py", "skills/poc_intraday_execution.py", "docs/prereg_poc_range_first_20261005.md"),
          variants=("next_open", "hl2", "range70_30", "regular_ticks", "intraday_odd_daily_proxy", "after_hours_odd"),
          gaps=("日高低是全日事後資訊，不能保證成交時刻或該價有量；逐筆也不等於自己的排隊與成交回報。",)),
    _item("capacity_resources", "分通路容量與資源鎖", "execution", "execution",
          "整股、零股分開限制參與率，保留委託占用的資金和名額，不把尚未成交賣款拿來買入；1% 是模型假設。",
          ("channel_volume", "scheduled_orders", "account_cash", "positions", "fee_schedule", "broker_reports"),
          ("skills/execution_resources.py", "skills/reservation_replay.py", "skills/residual_account_loop.py", "docs/prereg_execution_resources_20260924.md"),
          variants=("board_lot", "intraday_odd", "after_hours_odd", "residual_orders", "reserved_cash"),
          gaps=("完整零股價位成交／排隊及券商回報仍不足；容量公式不是實際成交認證。",)),
    _item("data_gap_policy", "來源缺口整單零成交", "execution", "execution",
          "來源不可用時整筆委託回滾為零成交並保留排除證據；買單資源鎖不回收，賣單保留真實持股與原出場訊號待重試。程式／帳務錯誤不可吞掉。",
          ("immutable_order_plan", "source_evidence", "execution_journal", "account_state"),
          ("skills/poc_gap_execution.py", "skills/poc_gap_audit.py", "docs/prereg_poc_gap_20261004.md"),
          gaps=("使用者授權的事後來源排除仍是研究限制，不是資料已修好或實際已成交；不能當作篩股票 alpha。",)),
    _item("corporate_accounting", "股利、配股與市場身分", "execution", "execution",
          "依權利日、發放日、上市日與公司行動原始條款處理應收、股數、成本及現金；市場身分按歷史日期核對。",
          ("official_corporate_announcements", "delivery_dates", "historical_market_identity", "fractional_share_terms", "account_state"),
          ("skills/replay_corporate_actions.py", "skills/pending_share_entitlements.py", "skills/market_identity_overlay.py", "docs/poc_range_corporate_terms_20261005.json"),
          gaps=("未定或未支付的碎股應收不能用來下單；行情還原因子不等於券商實際可賣股數。",)),
    _item("surge_diagnostics", "飆股覆蓋與買後路徑檢討", "diagnostic", "diagnostic",
          "以未來成熟窗口標記急漲、MFE／MAE、買後多久上漲及贏家覆蓋率，只能在訊號完成後檢討，不能回填為進場欄位。",
          ("independent_signal_ledger", "mature_future_price_paths", "research_cutoff"),
          ("skills/surge_capture.py", "skills/surge_anatomy.py", "skills/independent_signals.py", "docs/prereg_surge_capture_20260930.md"),
          variants=("surge_recall", "mfe_mae", "time_to_launch", "independent_signal_outcomes"),
          gaps=("尚未成熟事件保留未成熟；同股重疊訊號不當獨立樣本，這些結果欄位禁止參與當日掃描。",),
          interfaces=("independent_signals.observe",)),
)


# Adapter metadata replaces only explicitly ported IDs. The remaining research
# catalogue stays visible with its original data/implementation gaps.
from .public_rules import PUBLIC_CATALOG
from .research_rules import RESEARCH_CATALOG
_ADAPTERS = {row['id']: row for row in [*PUBLIC_CATALOG, *RESEARCH_CATALOG]}
if len(_ADAPTERS) != len(PUBLIC_CATALOG) + len(RESEARCH_CATALOG):
    raise ValueError('Duplicate scanner adapter IDs')
_BASE_CATALOG_IDS = {row['id'] for row in CATALOG}
CATALOG = tuple(_ADAPTERS.get(row['id'], row) for row in CATALOG) + tuple(
    row for row in [*PUBLIC_CATALOG, *RESEARCH_CATALOG] if row['id'] not in _BASE_CATALOG_IDS)
_PARTIAL_PORTS = {
    'first_volume_bar': (['first_volume_bar_price'],
        '純價量子版 first_volume_bar_price 已可掃描；原籌碼條件與接受事件冷卻語意未整套移植，不繼承原結果。'),
    'entry_quality': (['entry_not_extended', 'entry_strong_close'],
        '不過度乖離與嚴格紅K高位收盤已有獨立篩選；原候選交集、市場廣度與原同價K語意尚未整套移植。'),
    'liquidity_filter': (['liquidity_median50m', 'liquidity_prior50m', 'liquidity_persistent50m'],
        '三個流動性子條件已可獨立掃描；此父項指原候選交集比較，尚未自動套用到所有進場規則。'),
}
for _row in CATALOG:
    if _row['id'] in _PARTIAL_PORTS:
        _children, _note = _PARTIAL_PORTS[_row['id']]
        _row['adapter_variants'] = _children
        _row['data_gaps'] = [_note]


def get_catalog() -> list[dict]:
    """Return caller-owned metadata; mutating a UI payload cannot alter registry."""
    return deepcopy(list(CATALOG))
